// Code generated by MockGen. DO NOT EDIT.
// Source: metrics.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// RecordDatabaseOperationDuration mocks base method.
func (m *MockMetrics) RecordDatabaseOperationDuration(operation string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordDatabaseOperationDuration", operation, duration)
}

// RecordDatabaseOperationDuration indicates an expected call of RecordDatabaseOperationDuration.
func (mr *MockMetricsMockRecorder) RecordDatabaseOperationDuration(operation, duration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordDatabaseOperationDuration", reflect.TypeOf((*MockMetrics)(nil).RecordDatabaseOperationDuration), operation, duration)
}

// RecordExternalServiceCall mocks base method.
func (m *MockMetrics) RecordExternalServiceCall(serviceName string, success bool, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordExternalServiceCall", serviceName, success, duration)
}

// RecordExternalServiceCall indicates an expected call of RecordExternalServiceCall.
func (mr *MockMetricsMockRecorder) RecordExternalServiceCall(serviceName, success, duration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordExternalServiceCall", reflect.TypeOf((*MockMetrics)(nil).RecordExternalServiceCall), serviceName, success, duration)
}

// RecordPaymentCreated mocks base method.
func (m *MockMetrics) RecordPaymentCreated(paymentType, currency string, amount float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordPaymentCreated", paymentType, currency, amount)
}

// RecordPaymentCreated indicates an expected call of RecordPaymentCreated.
func (mr *MockMetricsMockRecorder) RecordPaymentCreated(paymentType, currency, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPaymentCreated", reflect.TypeOf((*MockMetrics)(nil).RecordPaymentCreated), paymentType, currency, amount)
}

// RecordPaymentFailed mocks base method.
func (m *MockMetrics) RecordPaymentFailed(errorType, paymentType string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordPaymentFailed", errorType, paymentType)
}

// RecordPaymentFailed indicates an expected call of RecordPaymentFailed.
func (mr *MockMetricsMockRecorder) RecordPaymentFailed(errorType, paymentType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPaymentFailed", reflect.TypeOf((*MockMetrics)(nil).RecordPaymentFailed), errorType, paymentType)
}

// RecordPaymentProcessingTime mocks base method.
func (m *MockMetrics) RecordPaymentProcessingTime(paymentType string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordPaymentProcessingTime", paymentType, duration)
}

// RecordPaymentProcessingTime indicates an expected call of RecordPaymentProcessingTime.
func (mr *MockMetricsMockRecorder) RecordPaymentProcessingTime(paymentType, duration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPaymentProcessingTime", reflect.TypeOf((*MockMetrics)(nil).RecordPaymentProcessingTime), paymentType, duration)
}

// RecordTransactionCompleted mocks base method.
func (m *MockMetrics) RecordTransactionCompleted(transactionType string, success bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordTransactionCompleted", transactionType, success)
}

// RecordTransactionCompleted indicates an expected call of RecordTransactionCompleted.
func (mr *MockMetricsMockRecorder) RecordTransactionCompleted(transactionType, success interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordTransactionCompleted", reflect.TypeOf((*MockMetrics)(nil).RecordTransactionCompleted), transactionType, success)
}

// RecordTransactionStarted mocks base method.
func (m *MockMetrics) RecordTransactionStarted(transactionType string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordTransactionStarted", transactionType)
}

// RecordTransactionStarted indicates an expected call of RecordTransactionStarted.
func (mr *MockMetricsMockRecorder) RecordTransactionStarted(transactionType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordTransactionStarted", reflect.TypeOf((*MockMetrics)(nil).RecordTransactionStarted), transactionType)
}

// UpdateWalletBalance mocks base method.
func (m *MockMetrics) UpdateWalletBalance(walletID, currency string, balance float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateWalletBalance", walletID, currency, balance)
}

// UpdateWalletBalance indicates an expected call of UpdateWalletBalance.
func (mr *MockMetricsMockRecorder) UpdateWalletBalance(walletID, currency, balance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWalletBalance", reflect.TypeOf((*MockMetrics)(nil).UpdateWalletBalance), walletID, currency, balance)
}
